PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX gip: <http://gipuzkoa.eus/resource/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
select ?g ?s ?p ?o where {
    ?g dcat:theme "museos".
    Graph ?g{?s ?p ?o .
    	?s foaf:name ?nombre .
        FILTER REGEX(?nombre, "Aitor Labajo") .
    }
} 
