prefix owl: <http://www.w3.org/2002/07/owl#>

select * where {
	{GRAPH <urn:local> {
            ?s ?p ?o .}}
    Union
  	{SERVICE <http://35.187.185.21:7200/repositories/abd-remoto> {
  		GRAPH <urn:remoto> {
                ?s ?p ?o .}}}

} 
