PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix prop: <http://gipuzkoa.eus/prop/>
prefix drm: <http://vocab.data.gov/def/drm#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

select ?museo ?trab ?num_trab
FROM <http://data.abd.ehu.eus/museoak>
where {
    ?museo prop:kopurua ?num_trab .
    ?trab foaf:name ?nombre .
    ?trab rdf:type foaf:person .
  	?trab <http://vocab.data.gov/def/drm#worksFor> ?museo  
      
    FILTER(?num_trab > "800"^^xsd:integer)
    FILTER REGEX(?nombre, "Mi.*")
   
}