PREFIX gip: <http://gipuzkoa.eus/resource/>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix gip_prop: <http://gipuzkoa.eus/prop/>

select ?ciudad ?alcalde
where{ 
    gip:gugenheim gip_prop:kokalekua ?ciudad .
	?ciudad owl:sameAs ?town
    service <http://dbpedia.org/sparql>{
		?town <https://dbpedia.org/ontology/leaderName> ?alcalde .
    }
}

